import { chromium } from "playwright";
import { mkdirSync } from "node:fs"; mkdirSync("shots",{recursive:true});
const b=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist","--enable-webgl","--no-sandbox"]});
const p=await b.newPage({viewport:{width:1100,height:620},deviceScaleFactor:1.4});
p.on("pageerror",e=>console.log("EXC",e.message));
await p.goto("http://localhost:4173/",{waitUntil:"domcontentloaded"});
await p.waitForFunction(()=>!!window.heistTD,null,{timeout:90000});
await p.waitForTimeout(4000);
const cam=(r,ax,ty,tz,tx)=>p.evaluate(([r,ax,ty,tz,tx])=>{const c=window.heistTD.camera.camera;c.radius=r;c.alpha=ax;c.beta=0.7;c.target.x=tx;c.target.y=ty;c.target.z=tz;},[r,ax,ty,tz,tx]);
const shot=async n=>{await p.screenshot({path:`shots/${n}.png`,timeout:120000});console.log("saved",n);};
await p.evaluate(()=>{const g=window.heistTD;g.ctx.state.gold=999999;
  for(const [id,i] of [["thief_03",5],["archer_02",6],["mage_blood_01",4]]) g.build(id,i);
  g.ctx.state.currentWave=28; g.waves.requestStart();});
await p.waitForTimeout(14000);
await cam(20,-Math.PI/2-0.5,0.5,-8.5,-4);
await p.waitForTimeout(1200);
await shot("roster-mixed");
await p.evaluate(()=>{const g=window.heistTD; g.ctx.state.currentWave=29; g.waves.requestStart();});
await p.waitForTimeout(13000);
await cam(24,-Math.PI/2-0.4,1,-9,-11);
await p.waitForTimeout(1200);
await shot("roster-boss");
await b.close();
